apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitoring-app-deployment
  labels:
    app: flask-monitoring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-monitoring-app
  template:
    metadata:
      labels:
        app: flask-monitoring-app
    spec:
      containers:
      - name: flask-monitoring-app
        image: flaskappacr.azurecr.io/flask-app:v3
        ports:
        - containerPort: 5000